
import ShareOfVoiceByMentionsDonut from "@/components/dashboard/ShareOfVoiceByMentions";
import ShareOfVoiceBySourceCard from "@/components/dashboard/ShareOfVoiceBySource";
import CompetitiveIntelligenceTable from "@/components/media/CompetitiveIntelligenceTable";
import React from "react";

const networks = [
  // Concurrent 1 - ATTIJARIWAFA BANK all platforms
  //   {
  //     network: "instagram",
  //     profil: "",
  //     username: "Attijariwafa bank",
  //     name: "Concurrent 1",
  //     followers: 156000,
  //     er: 2.8,
  //     avgEngage: 22000,
  //     avgViews: 245000,
  //     metrics: "87",
  //     growth: 5.2,
  //     activity: 12,
  //   },
  {
    network: "facebook",
    profil: "/Attijariwafa.png",
    username: "Attijariwafa bank",
    name: "Attijariwafa bank",
    followers: 420000,
    er: 2.1,
    avgEngage: 8500,
    avgViews: 125000,
    metrics: "82",
    growth: 3.8,
    activity: 8,
  },
  //   {
  //     network: "x",
  //     profil: "",
  //     username: "concurrent1_ma",
  //     name: "Concurrent 1",
  //     followers: 24000,
  //     er: 1.4,
  //     avgEngage: 1100,
  //     avgViews: 18000,
  //     metrics: "68",
  //     growth: -1.2,
  //     activity: 15,
  //   },
  //   {
  //     network: "tiktok",
  //     profil: "",
  //     username: "concurrent1.maroc",
  //     name: "Concurrent 1",
  //     followers: 112000,
  //     er: 6.5,
  //     avgEngage: 55000,
  //     avgViews: 1200000,
  //     metrics: "93",
  //     growth: 12.4,
  //     activity: 20,
  //   },
  {
    network: "youtube",
    profil: "/Attijariwafa.png",
    username: "Attijariwafa bank",
    name: "Attijariwafa bank",
    followers: 12000,
    er: 3.4,
    avgEngage: 1800,
    avgViews: 65000,
    metrics: "72",
    growth: 2.1,
    activity: 4,
  },
  {
    network: "linkedin",
    profil: "/Attijariwafa.png",
    username: "Attijariwafa bank",
    name: "Attijariwafa bank",
    followers: 32000,
    er: 2.6,
    avgEngage: 4200,
    avgViews: 38000,
    metrics: "76",
    growth: 4.7,
    activity: 6,
  },

  // Concurrent 2 - all platforms
  {
    network: "instagram",
    profil: "/cih.jpg",
    username: "cihbankma",
    name: "CIH BANK",
    followers: 72000,
    er: 2.4,
    avgEngage: 9500,
    avgViews: 98000,
    metrics: "76",
    growth: 3.1,
    activity: 8,
  },
  {
    network: "facebook",
    profil: "/cih.jpg",
    username: "CIH BANK",
    name: "CIH BANK",
    followers: 195000,
    er: 1.5,
    avgEngage: 3800,
    avgViews: 52000,
    metrics: "68",
    growth: -0.8,
    activity: 5,
  },
  {
    network: "x",
    profil: "/cih.jpg",
    username: "cihbank",
    name: "CIH BANK",
    followers: 11000,
    er: 0.9,
    avgEngage: 420,
    avgViews: 6200,
    metrics: "52",
    growth: 1.5,
    activity: 10,
  },
  //   {
  //     network: "tiktok",
  //     profil: "",
  //     username: "concurrent2.maroc",
  //     name: "Concurrent 2",
  //     followers: 58000,
  //     er: 5.8,
  //     avgEngage: 32000,
  //     avgViews: 580000,
  //     metrics: "84",
  //     growth: 8.7,
  //     activity: 15,
  //   },
  {
    network: "youtube",
    profil: "/cih.jpg",
    username: "CIH BANK",
    name: "CIH BANK",
    followers: 4200,
    er: 2.2,
    avgEngage: 520,
    avgViews: 22000,
    metrics: "56",
    growth: -2.3,
    activity: 2,
  },
  {
    network: "linkedin",
    profil: "/cih.jpg",
    username: "CIH BANK",
    name: "CIH BANK",
    followers: 15000,
    er: 1.8,
    avgEngage: 1800,
    avgViews: 16000,
    metrics: "63",
    growth: 2.9,
    activity: 4,
  },

  // Concurrent 3 - Banque Centrale Populaire - BCP
  //   {
  //     network: "instagram",
  //     profil: "",
  //     username: "concurrent3.ma",
  //     name: "Concurrent 3",
  //     followers: 54000,
  //     er: 2.6,
  //     avgEngage: 7800,
  //     avgViews: 72000,
  //     metrics: "73",
  //     growth: 6.4,
  //     activity: 10,
  //   },
  {
    network: "facebook",
    profil: "/bp.jpg",
    username: "Banque Populaire",
    name: "Banque Centrale Populaire - BCP",
    followers: 142000,
    er: 1.4,
    avgEngage: 2900,
    avgViews: 42000,
    metrics: "65",
    growth: 1.2,
    activity: 6,
  },
  {
    network: "x",
    profil: "/bp.jpg",
    username: "Banque Populaire",
    name: "Banque Centrale Populaire - BCP",
    followers: 8500,
    er: 0.8,
    avgEngage: 320,
    avgViews: 4800,
    metrics: "48",
    growth: -3.1,
    activity: 3,
  },
  //   {
  //     network: "tiktok",
  //     profil: "",
  //     username: "concurrent3.maroc",
  //     name: "Concurrent 3",
  //     followers: 45000,
  //     er: 5.2,
  //     avgEngage: 24000,
  //     avgViews: 420000,
  //     metrics: "81",
  //     growth: 15.2,
  //     activity: 18,
  //   },
  {
    network: "youtube",
    profil: "/bp.jpg",
    username: "Banque Populaire du Maroc",
    name: "Banque Centrale Populaire - BCP",
    followers: 3100,
    er: 1.9,
    avgEngage: 380,
    avgViews: 15000,
    metrics: "51",
    growth: 0.5,
    activity: 2,
  },
  {
    network: "linkedin",
    profil: "/bp.jpg",
    username: "Banque Centrale Populaire - BCP",
    name: "Banque Centrale Populaire - BCP",
    followers: 11000,
    er: 1.5,
    avgEngage: 1200,
    avgViews: 12000,
    metrics: "58",
    growth: 3.8,
    activity: 5,
  },

  // Concurrent 4 - all platforms
  //   {
  //     network: "instagram",
  //     profil: "",
  //     username: "concurrent4.ma",
  //     name: "Concurrent 4",
  //     followers: 38000,
  //     er: 2.0,
  //     avgEngage: 5200,
  //     avgViews: 48000,
  //     metrics: "68",
  //     growth: -1.5,
  //     activity: 6,
  //   },
  //   {
  //     network: "facebook",
  //     profil: "",
  //     username: "concurrent4maroc",
  //     name: "Concurrent 4",
  //     followers: 95000,
  //     er: 1.2,
  //     avgEngage: 1800,
  //     avgViews: 28000,
  //     metrics: "59",
  //     growth: 2.4,
  //     activity: 4,
  //   },
  //   {
  //     network: "x",
  //     profil: "",
  //     username: "concurrent4_ma",
  //     name: "Concurrent 4",
  //     followers: 5800,
  //     er: 0.7,
  //     avgEngage: 210,
  //     avgViews: 3200,
  //     metrics: "44",
  //     growth: -4.2,
  //     activity: 2,
  //   },
  //   {
  //     network: "tiktok",
  //     profil: "",
  //     username: "concurrent4.maroc",
  //     name: "Concurrent 4",
  //     followers: 28000,
  //     er: 4.8,
  //     avgEngage: 15000,
  //     avgViews: 280000,
  //     metrics: "78",
  //     growth: 9.8,
  //     activity: 12,
  //   },
  //   {
  //     network: "youtube",
  //     profil: "",
  //     username: "Concurrent4Maroc",
  //     name: "Concurrent 4",
  //     followers: 1800,
  //     er: 1.6,
  //     avgEngage: 220,
  //     avgViews: 9500,
  //     metrics: "46",
  //     growth: 1.1,
  //     activity: 1,
  //   },
  //   {
  //     network: "linkedin",
  //     profil: "",
  //     username: "concurrent4-maroc",
  //     name: "Concurrent 4",
  //     followers: 7500,
  //     er: 1.3,
  //     avgEngage: 780,
  //     avgViews: 8200,
  //     metrics: "54",
  //     growth: 5.6,
  //     activity: 3,
  //   },

  // CDM - all platforms
  {
    network: "instagram",
    profil: "/credit-du-maroc.png",
    username: "credit_du_maroc",
    name: "Crédit du Maroc",
    followers: 48000,
    er: 2.3,
    avgEngage: 6500,
    avgViews: 62000,
    metrics: "71",
    growth: 7.8,
    activity: 14,
  },
  {
    network: "facebook",
    profil: "/credit-du-maroc.png",
    username: "Crédit du Maroc",
    name: "Crédit du Maroc",
    followers: 125000,
    er: 1.3,
    avgEngage: 2400,
    avgViews: 35000,
    metrics: "62",
    growth: 4.3,
    activity: 8,
  },
  {
    network: "linkedin",
    profil: "/credit-du-maroc.png",
    username: "CREDIT DU MAROC",
    name: "Crédit du Maroc",
    followers: 125000,
    er: 1.3,
    avgEngage: 2400,
    avgViews: 35000,
    metrics: "62",
    growth: 4.3,
    activity: 8,
  },
  // {
  //     network: "tiktok",
  //     profil: "/pct.jpg",
  //     username: "massinart.maroc",
  //     name: "Massinart",
  //     followers: 35000,
  //     er: 5.0,
  //     avgEngage: 18000,
  //     avgViews: 340000,
  //     metrics: "79",
  //     growth: 18.5,
  //     activity: 22,
  // },
  {
    network: "youtube",
    profil: "/credit-du-maroc.png",
    username: "Crédit du Maroc Officiel",
    name: "Crédit du Maroc",
    followers: 2400,
    er: 1.8,
    avgEngage: 290,
    avgViews: 12000,
    metrics: "49",
    growth: 5.2,
    activity: 4,
  },
];

const page = () => {
  return (
    <div className="@container/main flex flex-col w-full ">
      <div className="">
        <h2 className="text-3xl font-semibold tracking-tight text-gray-900 dark:text-white inline-flex flex-col">
          Veille Concurrentielle
          <div className="flex flex-row gap-1 mt-2  mb-4">
            <div className="w-[20%] h-1 bg-[#f02cb9] rounded-full"></div>
            <div className="w-[10%] h-1 bg-[#35b9f4] rounded-full"></div>
          </div>
        </h2>
      </div>
      <div className="flex flex-col gap-5 w-full">
        <CompetitiveIntelligenceTable
          networks={networks}
          title="Analyse Concurrentielle"
        />
        <ShareOfVoiceByMentionsDonut />
        <ShareOfVoiceBySourceCard />

      </div>
    </div>
  );
};

export default page;
